### ISSUE TITLE
Textos para o site

### ISSUE THREAD

**Issue by ghost** [ReneFGJr/CentroIntegradoPesquisa#1]
PROGRAMAÇÃO CIENTÍFICA  (abaixo , serão incluídas outras palestras) 

06/10
09h20 / 10h
Conferência de Abertura
Título:  “Um mundo Mais Humano por meio da pesquisa”
Conferencista: Profa. Dra. Jucimeri Isolda Silveira - PUCPR

Resumo
Esta comunicação parte da reflexão crítica sobre os desafios da pesquisa e difusão de uma cultura em direitos humanos, num contexto de globalização com efeitos na manuteção e no aprofundamento da desigualdade social, e das práticas de intolerância e de violência, com diversas violações de direitos humanos. A Pontifícia Universidade Católica do Paraná vem estruturando a área estratégica em direitos humanos, processo indutor, ativador e articulador da pesquisa e de um conjunto de atividades, que explicitem o protagonimo de docentes e estudantes, e a relevância pública da universidade. Para tanto é preciso romper a departamentalização e a fragmentação, atuar de modo interdisciplinar na produção de pesquisas, com incidência no ensino e na extensão, em sintonia com os valores do densenvolvimento sustentável e dos direitos humanos, em benefício da sociedade. Processo que requer ambientes dialógicos, integradores, para a construção de novos saberes, novas práxis, alternativas que favoreçam a convivência pacífica, ética, responsável, solidária e igualitária, visando à distribuição equânime de bens, riqueza e poder, a valorização da diversidade e o reconhecimento das diferenças. As práxis transformadoras exigem reflexão/ação, a mediação crítica entre teoria, prática e ética, tendo como base os valores ético-políticos, alimentados por conhecimentos relevantes, explicativos e transformadores, na direção de um mundo efetivamente mais humano.

Palavas-chave: direitos humanos, pesquisa, práxis.

Jucimeri Isolda Silveira
É doutora em Serviço Social pela PUCSP, mestre em Sociologia pela UFPR, professora do Curso de Serviço Social e do Programa de Pós-Graduação em Direitos Humanos e Políticas Públicas, coordenadora do Núcleo de Direitos Humanos. Possui publicações em políticas públicas, especialmente em assistência social. Foi consultora pelo Programa das Nações Unidas para o Desenvolvimento junto ao Ministério de Desenvolvimento Social e Combate à Fome. Possui experiência em direitos humanos e políticas púbicas, na área de planejamento, gestão pública e trabalho social.

Palestra de Encerramento
Prof. Dr. Harry Alberto Bollmann (PUCPR)

Título: DIREITOS HUMANOS, CIDADES E DESENVOLVIMENTO SUSTENTÁVEL

Vivemos em uma época de incertezas, onde até mesmo os direitos humanos mais elementares precisam ser reconquistados dentro da perturbada e impessoal sociedade moderna. Ao mesmo tempo, a constante produção teórica do utopismo das cidades justas como um local de realização da plena condição humana, bem como da equilibrada convivência com o meio ambiente e suas funções, acentua uma realidade diacrônica entre o discurso e a ação, entre o sonho e a realidade. A cidade de hoje já não é mais vivenciada e nem entendida como antes. Elos de pertencimento e de respeito se romperam. A cidade se transformou mais em um objeto de consumo, ou um objeto orientado para o consumo dos bens e serviços nela transacionados. Para alguns mais saudosistas, a cidade (antiga) está morta, embora persista em um estado alienado, como um ente difuso e amorfo, pontuado por inúmeras crises. Neste ponto, a universidade precisa desempenhar seu duplo papel: o de pensar e de discutir os fundamentos de um novo projeto urbano sustentável que consiga reconectar as pessoas com o seu espaço vital, sem esquecer o de buscar as soluções emergenciais para as crises da atualidade.

Prof. Dr. Harry Alberto Bollmann  - Engenheiro Civil pela PUCPR, mestrado em Engenharia Hidráulica e Saneamento pela USP e doutorado em Recursos Hídricos e Saneamento Ambiental pela UFRGS. Atualmente é professor Titular da PUCPR junto ao Mestrado e Doutorado em Gestão Urbana, e ao Curso de Graduação em Engenharia Ambiental. É membro do LEAD Institute International desde 1994, atuando em temas correlacionados ao Meio Ambiente e Desenvolvimento Sustentável. É também co-editor da Revista URBE - Revista Brasileira de Gestão Urbana da PUCPR, e revisor das revistas Árvore (Scielo) da Universidade Federal de Viçosa, e da Revista Engenharia Sanitária e Ambiental (Scielo) da Associação Brasileira de Engenharia Sanitária e Ambiental. Faz parte do Comitê dos Mananciais da Região Metropolitana de Curitiba e da Câmara Técnica do Karst junto à Coordenação da Região Metropolitana de Curitiba. Tem experiência na área de Engenharia Ambiental, com ênfase em Planejamento Ambiental Integrado, atuando principalmente nos seguintes temas: planejamento dos recursos hídricos, assentamentos urbanos sustentáveis, monitoramento da qualidade das águas, avaliação ambiental, bacias hidrográficas urbanas e recuperação de áreas degradadas.

**Comment by ElizandroLima** [comment]
Texto incluída na pagina de programação no site!

**Comment by ElizandroLima** [comment]
Concluído
