### ISSUE TITLE
Incluir o FAQ

### ISSUE THREAD

**Issue by ghost** [ReneFGJr/CentroIntegradoPesquisa#2]
1- Existe algum modelo de Painel e apresentação Oral?
Sim, verifique no link abaixo em “modelos de documentos”. Preste atenção, este ano os pôsteres deverão ser confeccionados em papel.
http://www.pucpr.br/pesquisacientifica/iniciacaocientifica/modelosdedocumentos.php 

2 - Quando terei que apresentar o meu trabalho?
Verifique a data e horário que está disponível no site www2.pucpr.br/reol/semic no menu “SUMÁRIO” e digite (CTLR+F) para localizar seu nome. Após localizar o nome verifique qual é seu código de trabalho, com ele você deverá clicar em “PROGRAMAÇÃO” para localizar então o horário de apresentação Oral ou Pôster.

3 -  Não posso apresentar o trabalho na data indicada, como devo proceder?
Não será possível mudanças no cronograma, o aluno que não participar da apresentação não receberá a declaração de participação no programa PIBIC/PIBITI conforme cadernos de normas, ficando o Comitê Gestor responsável pela análise de devolução de bolsas em caso de alunos bolsistas. Em casos extremos o professor orientador deverá encaminhar uma justificativa à coordenação e deverá apresentar o trabalho no lugar do aluno.

4 – Quantas apresentações devo assistir para ter a declaração de participação no evento caso não eu não seja aluno PIBIC/PIBITI e queira a declaração como ouvinte?
O aluno que quiser participar como ouvinte deverá assistir obrigatoriamente pelo menos 50% das apresentações oral, palestras, minicurso e/ou mesa redonda.
**\* Sessões de pôster NÃO contabilizam como frequência para completar os 50% de participação no evento. 
5 - Sou aluno PIBIC/PIBITI e irei apresentar, terei direito à declaração?
Sim, alunos que apresentarão seus trabalhos no evento receberão a declaração de conclusão e participação no programa PIBIC/PIBITI, porém caso queiram a declaração de participação no evento SEMIC 2015, deverão obrigatoriamente participar em 50 % do evento, assim receberão duas declarações.

6 – Quantas apresentações deverei assistir para participar 50% do evento?
Para ter 50% de presença o aluno deverá assistir pelo menos 07 (sete) blocos de apresentação. Seja oral, palestra, minicurso e/ou mesa redonda, porém, a participação somente será contabilizada caso o aluno permaneça durante o bloco inteiro (início ao fim) de apresentação. A equipe de apoio está terminantemente proibida de abrir qualquer tipo de exceção, caso o aluno queira sair da sala antes de finalizar o bloco. Nosso sistema é altamente resolutivo e contempla saídas para ir ao banheiro, tomar água etc, porém o aluno não poderá permanecer por um período superior a 15 minutos fora da sala, pois sua entrada será automaticamente cancelada pelo sistema. Entradas e saídas nas salas durante as apresentações poderão atrapalhar os colegas, portanto evitem ao máximo.

6 – Posso validar o certificado do SEMIC como horas complementares? Quantas horas é válido?
Cada aluno deverá apresentar  a declaração de participação no programa e/ou ouvinte na coordenação de seu curso de graduação  para validar as horas. A coordenação do PIBIC não determina a quantidade de horas a serem validadas.

CERTIFICADO
1 - Quando terei acesso ao meu certificado?
O certificado será disponibilizado no site do evento a partir do dia 25/10/2015, e poderá ser obtido no painel do usuário. Somente usuários com credenciamento efetivo terão direito ao certificado de participação, portanto todos os alunos deverão obrigatoriamente efetuar o credenciamento a partir do dia 05/10/2015 conforme instruções no site do evento.

2) Tenho direito a Certificado de Participação?
A inscrição com a sua respectiva apresentação dará direito ao Certificado de Participação no evento desde que as regras acima sejam respeitadas.

**Comment by ElizandroLima** [comment]
Pagina criada no site

**Comment by ElizandroLima** [comment]
Concluído
