### ISSUE TITLE
Inserir Logomarca do SENAI para ser colocado no site e nos materiais

### ISSUE THREAD

**Issue by ghost** [ReneFGJr/CentroIntegradoPesquisa#3]
![senai azul](https://cloud.githubusercontent.com/assets/7387756/9820177/8ccd5c40-5888-11e5-87fb-dff81b054f01.JPG)
![senai azul](https://cloud.githubusercontent.com/assets/7387756/9820188/a3e2f8e0-5888-11e5-9007-764ced0d3a94.JPG)

**Comment by ElizandroLima** [comment]
Finalizado
