### ISSUE TITLE
Programação PUC Cultural para colocar no site

### ISSUE THREAD

**Issue by ghost** [ReneFGJr/CentroIntegradoPesquisa#4]
PROGRAMAÇÃO  PUCPR CULTURAL

Abertura 
Participação performática do Coral Champagnat da PUCPR
com o grupo musical de pesquisadores-artistas da PUCPR
Atuações da Maestrina ROSEMERI PAESE e dos Músicos MARCELO MIRA, RODRIGO REIS, ADRIANO AKIRA e EDUARDO SCHEEREN.

Apresentação na Abertura do SEMIC no TUCA- Teatro da PUCPR: 06/10 – 3af-feira – 8h30

TRANSCENDENDO NA ESTRELA - CONSTELAÇÕES SISTÊMICAS
Vivência grupal conduzida pelas consteladoras Marusa Helenna da Graça e Vera Boeing na Casa Estrela, o local mágico no marco zero do campus da PUCPR.
Com o tema “Um Lugar para os Excluídos – Somos Todos Um”, a Vivência é baseada nos conceitos e na técnica de Bert Hellinger, o criador das Constelações Familiares. Marusa Gonçalves e Vera Boeing são nomes locais de referência no Brasil em Constelações Sistêmicas. 

A Casa Estrela, patrimônio da Arquitetura local, restaurada e reedificada pela PUCPR, única no mundo por sua peculiaridade na intenção da forma, foi construída manualmente em madeira por Augusto Gonçalves de Castro (perito contador) e sua esposa Dionízia Azulay no início da década de 30. A família Castro era Esperantista, Teosofista e adepta da Fraternidade Universal.

Sessões (com duração de 90 minutos): 
06/10 – terça-feira – 14h
07/10 – quarta-feira – 9h

Inscrições e retirada de ingressos (40 vagas por sessão):

CONCERTO DIDÁTICO - DO BARROCO AO CONTEMPORÂNEO – Orquestra da PUCPR sob a direção do Maestro Paulo Torres
A apresentação didática vai mostrar o desenvolvimento ao longo da História de uma grande orquestra sinfônica e os grandes compositores dos períodos Barroco, Clássico, Romântico e Moderno em ordem cronológica.

Apresentação no TUCA- Teatro da PUCPR (com duração aproximada de 60 minutos):  06/10 – 3ª.feira – 15h

Não é necessário retirar ingresso (lotação do TUCA: 500 lugares)

![image](https://cloud.githubusercontent.com/assets/7387756/9820391/0f25d7a2-588a-11e5-80db-3938b4f42c96.png)

![image](https://cloud.githubusercontent.com/assets/7387756/9820394/139cd236-588a-11e5-8ce8-cf99230b28ef.png)

Documento: PROGRAMAÇÃO  PUCPR CULTURAL - versão final (1)

**Comment by ElizandroLima** [comment]
Pendência: Verificar coincidência de horários de eventos no dia 06/10

**Comment by ElizandroLima** [comment]
Resolvido
