### ISSUE TITLE
Programação cultural - Incluir

### ISSUE THREAD

**Issue by ghost** [ReneFGJr/CentroIntegradoPesquisa#5]
DO ERUDITO AO POPULAR - CONCERTO DA ORQUESTRA DA PUCPR
AUDIÇÃO COMENTADA PELO MAESTRO, VIOLINISTA E PROFESSOR DA PUCPR DR. PAULO TORRES

A apresentação didática vai mostrar o desenvolvimento ao longo da História de uma grande orquestra sinfônica e os grandes compositores dos períodos Barroco, Clássico, Romântico e Moderno em ordem cronológica.

Apresentação no TUCA- Teatro da PUCPR (com duração aproximada de 60 minutos):

 06/10 – terça-feira – 15h

Não é necessário retirar ingresso (lotação do TUCA: 500 lugares)

**Comment by ElizandroLima** [comment]
Concluído
