### ISSUE TITLE
Inserir tela para incorporação e alteração de conta corrente

### ISSUE THREAD

**Issue by ReneFGJr** [ReneFGJr/CentroIntegradoPesquisa#8]
Módulo: Usuários
o sistema deve possibilitar a incorporação de uma conta corrente caso o esta não exista ou alterar a conta já existente.

Deve ser inserido um registro de histórico "us_histórico"

**Comment by ElizandroLima** [comment]
Criado função para manutenção de dados de conta bancária:

![image](https://cloud.githubusercontent.com/assets/10881293/11570744/04c6f9c0-99e0-11e5-967d-45c2d8218ed2.png)

**Comment by ElizandroLima** [comment]
Concluído
